inherit_from: .rubocop_todo.yml


AllCops:
  Exclude:
    - Gemfile
    - Guardfile
    - script/**/*
    - 'node_modules/*'
    - 'vendor/**/*'
    - lib/tasks/*
    - features/**/*
    - db/**/*
    - bin/**/*
    - config/**/*
    - app/views/**/*.json.jbuilder
    - volumes/**/*
    - old/*/
    - old/**/*
    - scrapers/*

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: False
Style/Documentation:
  Enabled: False
Style/HashSyntax:
  Enabled: False

Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
