# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
Style/MissingRespondToMissing:
  Exclude:
    - 'app/models/json_match.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'spec/rails_helper.rb'
